language: python
python:
  - "2.7"
  - "3.5"
dist: trusty

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda${TRAVIS_PYTHON_VERSION:0:1}-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda install --yes python="$TRAVIS_PYTHON_VERSION" numpy scipy matplotlib networkx nose pandas pydot pydotplus requests pyparsing
  - conda install --yes -c marufr python-igraph
  - mkdir -p ~/.config/matplotlib
  - echo "backend:Agg" > ~/.config/matplotlib/matplotlibrc
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install nose-exclude
  - pip install nose-timer

install:
  - python setup.py build --build-lib=build/lib
script:
 - travis_wait 45 nosetests build/lib/py2cytoscape/tests --with-coverage --cover-inclusive --cover-package=build/lib/py2cytoscape --logging-level=INFO --with-timer
after_success:
  - coveralls
